name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install clang-format
        run: sudo apt-get update && sudo apt-get install -y clang-format

      - name: Check code formatting with clang-format
        run: |
          find . -name '*.cpp' -o -name '*.h' | xargs clang-format --dry-run --Werror
          
      - name: Check for uncommitted changes (code style violations)
        run: |
          git diff --exit-code || echo "Code style violations detected, please fix them."
          
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential python3 python3-pip libgl1-mesa-dev libglu1-mesa-dev

      - name: Install aqtinstall (Qt installer)
        run: |
          pip3 install aqtinstall

      - name: Upgrade aqtinstall
        run: |
          pip3 install --upgrade aqtinstall

      - name: Install Qt 6.5.2 with all modules
        run: |
          aqt install-qt linux desktop 6.5.2 gcc_64 --outputdir $HOME/Qt --modules all

      - name: Set up Qt environment
        run: echo "$HOME/Qt/6.5.2/gcc_64/bin" >> $GITHUB_PATH

      - name: Configure project with qmake
        run: |
          cd $GITHUB_WORKSPACE
          qmake FinTrack.pro

      - name: Build project
        run: |
          make
          
      - name: Make test executable
        run: |
          chmod +x ./tests/tst_homewindow
          
      - name: Run tests
        run: |
          ./tests/tst_homewindow
